config/routes.rb
ActionController::Routing::Routes.draw do |map|

  map.connect "/lists/:list_id/items/:id/remove_label/:label_id", :controller => 'items', :action => 'remove_label'
  map.connect "/lists/:list_id/items/:id/start_task/", :controller => 'items', :action => 'start_task'
  
  map.resources :lists do |list|
    list.resources :items do |label|
      label.resources :labels
    end
  end

  map.resources :labels

  root :to => "lists#index"

end

app/models/item.rb
class Item < ActiveRecord::Base
  STATUSES = ["", "started", "finished"]
  belongs_to :list
  has_and_belongs_to_many :labels

  validates_presence_of :name
end

app/models/label.rb
class Label < ActiveRecord::Base
  has_and_belongs_to_many :items

  validates_presence_of :name
  validates_presence_of :color
  validates_format_of :color, :with => /^(\d|[a-f]|[A-F])+$/
end

app/models/list.rb
class List < ActiveRecord::Base
  has_many :items, :dependent => :destroy

  validates_presence_of :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private

  def authenticate
    authenticate_or_request_with_http_basic do |user_name, password|
      user_name == 'getitdone' && password == 'gititdun'
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def login
    
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  helper_method :remove_label

  def new
    @list = List.find params[:list_id]
    @item = Item.new
  end

  def create
    @list = List.find params[:list_id]
    @item = @list.items.create params[:item]

    respond_to do |format|
      if @item.save
        format.js
        format.html { redirect_to lists_path }
      else
        redirect_to lists_path
      end
    end
  end

  def edit
    @list = List.find params[:list_id]
    @item = Item.find params[:id]
  end

  def update
    @list = List.find params[:list_id]
    @item = Item.find params[:id]
    params[:item][:label_ids] ||= []

    respond_to do |format|
      if @item.update_attributes params[:item]
        format.js
        format.html { redirect_to lists_path, :notice => "Item updated" }
      else
        redirect_to lists_path
      end
    end
  end

  def destroy
    @list = List.find params[:list_id]
    @item = Item.find params[:id]
    @item.destroy

    respond_to do |format|
      format.js
      format.html { redirect_to lists_path }
    end
  end

  def start_task
    @list = List.find params[:list_id]
    @item = Item.find params[:id]
    @item.status = 1

    respond_to do |format|
      if @item.save
        format.js
        format.html { redirect_to lists_path }
      end
    end
  end

  def remove_label
    @item = Item.find params[:id]
    @item.labels.delete(Label.find(params[:label_id]))

    redirect_to lists_path
  end
end

app/controllers/labels_controller.rb
class LabelsController < ApplicationController

  def new
    @label = Label.new
  end

  def create
    @label = Label.new params[:label]
    if @label.save
      redirect_to lists_path
    else
      redirect_to new_label_path
    end
  end

  def delete
    @item = Item.find params[:item_id]
    @item.labels.delete params[:id]
  end
  
  def destroy
    @label = Label.find params[:id]
    @label.destroy
    
    respond_to do |format|
      format.js
      format.html { redirect_to lists_path }
    end
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    @lists = List.all
  end

  def show
    @list = List.find params[:id]
    @items = @list.items.select { |i| i.status != 2 }
    @finished = @list.items.select { |i| i.status == 2 }
  end
  
  def new
    @list = List.new
  end

  def create
    @list = List.new params[:list]
    if @list.save
      redirect_to lists_path, :notice => "New list created"
    else
      render :action => "new"
    end
  end

  def destroy
    @list = List.find params[:id]
    @list.destroy

    redirect_to lists_path, :notice => "List destroyed"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper

end

app/helpers/labels_helper.rb
module LabelsHelper
end

app/views/items/_form.html.erb
<td class="label"></td>
<td class="name">
  <%= form_for [list, item], :remote => true do |f| %>
    <%= f.text_field :name, :size => 48, :id => defined?(new) ? "new_item_name" : "item_#{item.id}_name" %>
    <%= f.submit %>
    <ul>
      <% Label.all.each do |label| %>
        <li class="label-<%= label.id %>">
          <%= check_box_tag "item[label_ids][]", label.id, item.labels.include?(label), { :id => defined?(new) ? "item_label_#{label.id}" : "item_#{item.id}_label_#{label.id}", :class => defined?(new) ? "new-item-label" : "" } %>
          <span style="background: #<%= label.color %>"><%= f.label (defined?(new) ? "label_#{label.id}" : "#{item.id}_label_#{label.id}"), "#{label.name}" %></span>  <%= link_to('delete', label_path(label), :method => :delete, :remote => true) if defined?(new) %>
        </li>
      <% end %>
      <li>
        <%= link_to "+ new label", new_label_path %>
      </li>
  <% end %>
  </ul>
</td>
<td class="edit"></td>

app/views/items/_item.html.erb
<tr id="<%= "item_#{item.id}" %>" <%= "class=item-#{Item::STATUSES[item.status]}" if item.status == 1 %>>
  <td class="label">
    <ul>
      <% item.labels.each do |label| %>
        <li class="label-<%= label.id %>"><span style="background: #<%= label.color %>"><%= label.name %> <%= link_to '×', "/lists/#{list.id}/items/#{item.id}/remove_label/#{label.id}" %></span></li>
      <% end %>
    </ul>
  </td>
  <td class="name"><%= auto_link h item.name %> <b id="<%= "item_#{item.id}_status" %>"><%= Item::STATUSES[item.status] %></b></td>
  <td class="edit"><%= link_to 'e', edit_list_item_path(list, item), :remote => true %> <%= link_to '▸', "/lists/#{list.id}/items/#{item.id}/start_task", :remote => true %> <%= link_to '×', list_item_path(list, item), :method => :delete, :remote => true %></td>
</tr>

app/views/items/create.js.erb
$('#new_item_row').after("<%= escape_javascript(render :partial => "item", :locals => { :item => @item, :list => @list, :new => true }) %>");
$('#new_item_name').attr('value', '').focus();
$('.new-item-label').removeAttr('checked');

app/views/items/destroy.js.erb
$('#item_<%= @item.id %>').fadeOut('fast', function() {$('#item_<%= @item.id %>').remove();});

app/views/items/edit.html.erb
<%= render :partial => "layouts/page_header", :locals => { :header => @item.name } %>

<div id="content">
  <h1>Editing <%= @item.name %> in <%= @item.list.name %></h1>

  <%= render 'form' %>
</div>

app/views/items/edit.js.erb
$('#item_<%= @item.id %>').after("<tr id=\"<%= "item_#{@item.id}_edit" %>\"><%= escape_javascript(render :partial => "form", :locals => { :item => @item, :list => @list }) %></tr>");
$('#item_<%= @item.id %>').remove();

app/views/items/new.html.erb
<%= render :partial => "layouts/page_header", :locals => { :header => "New Item" } %>

<div id="content">
  <h1>New item in <%= @list.name %></h1>

  <%= render 'form' %>
</div>

app/views/items/start_task.js.erb
$('#item_<%= @item.id %>').addClass('item-<%= Item::STATUSES[@item.status] %>');
$('#item_<%= @item.id %>_status').html('<%= Item::STATUSES[@item.status] %>');

app/views/items/update.js.erb
$('#item_<%= @item.id %>_edit').after("<%= escape_javascript(render :partial => "item", :locals => { :item => @item, :list => @list }) %>");
$('#item_<%= @item.id %>_edit').remove();

app/views/labels/destroy.js.erb
$('.label-<%= @label.id %>').fadeOut('fast', function() {$('.label-<%= @label.id %>').remove();});

app/views/labels/new.html.erb
<h1>New label</h1>

<%= form_for @label do |f| %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :color %><br />
    <%= f.text_field :color %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/layouts/_page_header.html.erb
<div id="page_header">
  <h2><%= header %></h2>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Get It Done!</title>
  <%= stylesheet_link_tag :all %>
  <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script>
  <%= javascript_include_tag "rails" %>
  <%= csrf_meta_tag %>
	<%= stylesheet_link_tag "styles" %>
</head>
<body>
<div id="container">
  <div id="header" class="clearfix">
    <h1>Get It Done!</h1>
  </div>
  <%= yield %>
</div>
</body>
</html>

app/views/lists/index.html.erb
<%= render :partial => "layouts/page_header", :locals => { :header => "List Index" } %>

<div id="content">
  <% if @lists.length == 0 %>
    <p>You don't have any lists.</p>
  <% else %>
    <ul>
    <% @lists.each do |list| %>
      <ul>
        <li><%= link_to list.name, list_path(list) %></li>
      </ul>
      <hr/>
    <% end %>
    </ul>
  <% end %>
  <%= link_to 'Make a new list.', new_list_path %>
</div>

app/views/lists/new.html.erb
<h2>Makin' a list</h2>

<%= form_for @list do |f| %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lists/show.html.erb
<%= render :partial => "layouts/page_header", :locals => { :header => @list.name } %>

<div id="content">
  <table id="item_list">
    <tr>
      <th class="label">Labels</th>
      <th class="name">Item</th>
      <th class="edit">Edit</th>
    </tr>
    <tr id="new_item_row" class="new-item-row">
      <%= render :partial => "items/form", :locals => { :list => @list, :item => Item.new, :new => true } %>
    </tr>
    <%= render :partial => "items/item", :collection => @items.reverse, :locals => { :list => @list } %>
  </table>
  <hr/>
</div>